database:
  host: "localhost"           # The database server address (e.g., localhost or IP)
  port: 3306                  # The port MySQL listens on (default: 3306)
  name: "epicquest_rpg"       # The name of the database
  username: "root"            # The username for the database
  password: "password"        # The password for the database

options:
  use-ssl: false              # Set to true if SSL is required
  auto-reconnect: true        # Automatically reconnect if the connection is lost
