name: Maven Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Extract commit hash
        run: echo "COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Update version in pom.xml
        run: |
          mvn versions:set -DnewVersion=0.1-ALPHA-${{ github.run_number }}-SNAPSHOT

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: epicquest-rpg-RELEASE-${{ env.COMMIT_HASH }}
          path: target/*.jar
          retention-days: 30

      - name: Create GitHub Pre-Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: RELEASE
          release_name: "Pre-Release ${{ env.COMMIT_HASH }}"
          draft: false
          prerelease: true  # 👈 This marks it as a pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: RELEASE
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -Drevision=${{ github.run_number }}-SNAPSHOT -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
